import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import { MobileNav } from "@/components/mobile-nav";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-x-hidden flex min-h-screen flex-col`}
      >
        <header>
          <MainNav />
          <MobileNav />
        </header>
        <main className="flex-1 pt-[65px] lg:pt-[73px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
